### ISSUE TITLE
This is very nice lib, I have a question about BinaryWriter

### ISSUE THREAD

**Issue by KaivnD** [Meigyoku-Thmn/CSBinary#1]
As I can see the `File` function require a file descriptor in `.d.ts` file:

```ts
/** A thin wrapper of \<cstdio\>, implementing the IFile interface. It uses binary mode only. */
export declare const NativeFile: new (fd: number) => IFile;
/** Factory function to create NativeFile instance */
export declare function File(fd: number): IFile;
```

Is it even possible to passing a existing `Uint8Array` to `File` and write file later, like this?
```js
const existingUint8Array = new Uint8Array()
const file = File(existingUint8Array)
const bw = new BinaryWriter(file)
file.save('filename')
bw.close()
```

PS: I'm trying to write a binary file with node backend when browser frontend http request, so I want to find a way to do this magic work in browser.

**Comment by KaivnD** [comment]
Oh, wait! I think I just found the way.

This isn't about what passing to `BinaryWriter`, is what will happen after `new BinaryWriter()`, so forget what I said before.

**Comment by Meigyoku-Thmn** [comment]
I don't quite understand what you need, but if you want something like MemoryStream in .NET, then you can implement the IFile interface, then pass the instance into BinaryWriter/BinaryReader constructor.
